name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - macos
          - ubuntu
          - windows
        toolchain:
          - stable
          - 1.86.0
        features:
          - tokio1
          - std

    name: "Test on ${{ matrix.platform }} with Rust ${{ matrix.toolchain }} (feat: ${{ matrix.features }})"
    runs-on: "${{ matrix.platform }}-latest"

    steps:
      - uses: actions/checkout@v4

      - name: Configure Rust
        run: |
          rustup toolchain install --profile minimal --no-self-update nightly
          rustup toolchain install --profile minimal --no-self-update ${{ matrix.toolchain }}
          rustup default ${{ matrix.toolchain }}
          rustup component add clippy

      - uses: Swatinem/rust-cache@v2

      - run: tests/multiproc_helper.rs 1 1
      - run: cargo test --features ${{ matrix.features }} --all-targets
      - run: cargo clippy --features ${{ matrix.features }}

  formatting:
    name: Fmt check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure Rust
        run: |
          rustup toolchain install --profile minimal --no-self-update stable
          rustup default stable

      - run: cargo fmt --check

